---
kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: dockage/gearmand
      auto_tag: true

---
kind: pipeline
name: notify

steps:
  - name: microbadger
    image: plugins/webhook
    settings:
      urls:
        - https://hooks.microbadger.com/images/dockage/gearmand/LEIsc8IM3IAx1yRouxAGoOOlFRA=

depends_on:
  - default
